exports.OPTIONS = {
  LOOKUP_CHILD: 'LOOKUP_CHILD',
  LOOKUP_POSTERITY: 'LOOK_POSTERITY',
  LOOKUP_BEFORE: 'LOOKUP_BEFORE',
  LOOKUP_AFTER: 'LOOKUP_AFTER',
  MATCH_ELEMENT: 'MATCH_ELEMENT',
  MATCH_ID: 'MATCH_ID',
  MATCH_CLASS: 'MATCH_CLASS'
}